#!/usr/bin/env python3
"""
Generate a mesh/boundary_ids_antarctica_<COARSE>_<FINE>_buffered<N>.json
sidecar from a generated Antarctica .msh file.

The mesh pipeline (mesh_antarctica.py / icepack2_tools.mesh) tags each
boundary segment as a gmsh physical group named "Calving_N" or "Other_N",
and the ice surface as "Ice". In gmsh's MSH 2.2 format the physical-group
tag is exactly the integer boundary marker that Firedrake exposes, so the
downstream solvers' boundary_ids sidecar is just that name->tag map binned
into calving-front vs. other (land/grounding) boundaries:

    {"calving": [<tags>], "other": [<tags>]}

The boundary topology (and thus the sidecar contents) depends on the
outline buffer (`ISMIP7_BUFFER_M`) used to build the mesh, so the mesh and
sidecar filenames are both tagged with the exact resolution and buffer size
(see mesh_naming.py) — a sidecar built for one mesh/buffer is not valid for
a different one.

This file is read by diagnostic_solve, inversion_icepack2, simulation,
run_control, lcurve_icepack2, gl_sensitivity and run_eigendec, but no
script in the repo produced it — this generator fills that gap.

Usage:
    python scripts/make_boundary_ids.py
    ISMIP7_BUFFER_M=0 python scripts/make_boundary_ids.py
    ISMIP7_MESH=path/to/mesh.msh ISMIP7_BNDIDS=path/to/out.json python scripts/make_boundary_ids.py
"""

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))))
from icepack2_tools.runconfig import lc as _lc, lc_coarse as _lc_coarse
from mesh_naming import get_buffer_m, mesh_filename, bndids_filename

lc = _lc()
lc_coarse = _lc_coarse()


def parse_physical_names(mesh_fn):
    """Return list of (dim, tag, name) from a MSH file's $PhysicalNames block."""
    entries = []
    with open(mesh_fn) as f:
        in_block = False
        for line in f:
            line = line.strip()
            if line == "$PhysicalNames":
                in_block = True
                next(f)  # skip the count line
                continue
            if line == "$EndPhysicalNames":
                break
            if in_block:
                m = re.match(r'(\d+)\s+(\d+)\s+"(.*)"', line)
                if m:
                    entries.append((int(m.group(1)), int(m.group(2)), m.group(3)))
    return entries


def write_boundary_ids(mesh_fn, out_fn):
    """Parse a mesh's $PhysicalNames and write {calving, other} ids to out_fn.

    Importable so the mesh pipeline can emit a sidecar that always matches the
    mesh it just wrote. Returns the {"calving": [...], "other": [...]} dict.
    """
    print(f"Reading physical groups from {mesh_fn}")
    entries = parse_physical_names(mesh_fn)
    if not entries:
        raise ValueError(
            f"No $PhysicalNames block found in {mesh_fn}. "
            "Was the mesh generated by mesh_antarctica.py?"
        )

    calving, other, skipped = [], [], []
    for dim, tag, name in entries:
        if dim != 1:
            continue  # surfaces ("Ice") and any interior curves are not BCs
        if name.startswith("Calving"):
            calving.append(tag)
        elif name.startswith("Other"):
            other.append(tag)
        else:
            skipped.append((tag, name))

    if skipped:
        print(f"  Warning: {len(skipped)} unrecognized boundary group(s): "
              f"{skipped[:5]}{' ...' if len(skipped) > 5 else ''}")

    bnd_ids = {"calving": sorted(calving), "other": sorted(other)}
    with open(out_fn, "w") as f:
        json.dump(bnd_ids, f, indent=2)
    print(f"  {len(calving)} calving + {len(other)} other boundaries")
    print(f"Wrote {out_fn}")
    return bnd_ids


def main():
    buffer_m = get_buffer_m()
    mesh_fn = os.environ.get(
        "ISMIP7_MESH", mesh_filename(lc_coarse, lc, buffer_m)
    )
    out_fn = os.environ.get("ISMIP7_BNDIDS", bndids_filename(lc_coarse, lc, buffer_m))
    write_boundary_ids(mesh_fn, out_fn)


if __name__ == "__main__":
    main()
